edition = "2021"
fn_single_line = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
group_imports = "One"
hex_literal_case = "Lower"
imports_granularity = "Item"
normalize_comments = false
overflow_delimited_expr = true
reorder_impl_items = true
single_line_if_else_max_width = 80
single_line_let_else_max_width = 80
struct_field_align_threshold = 0
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = false
